import { readFile } from "node:fs/promises";
import path from "node:path";
import { ImageResponse } from "next/og";
import { siteConfig } from "@/lib/site";

// nodejs runtime so we can read the bundled avatar from /public — no need
// to hit GitHub at request time, and the OG image works offline.
export const runtime = "nodejs";
export const alt = siteConfig.name;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

type Params = Promise<{ locale: string }>;

// Locale-aware OpenGraph image — generated by Next via the file convention.
// Uses the same "paper" palette as the live site: warm cream background,
// ink text, hairline rule, amber accent.
export default async function OG({ params }: { params: Params }) {
  const { locale } = await params;
  const isPt = locale === "pt";

  // Pre-fetched palette to mirror globals.css `:root` (light theme).
  const PAPER = "#FAF6EB";
  const INK = "#2A2520";
  const MUTED = "#847B6E";
  const RULE = "#D6CDBF";
  const ACCENT = "#B45309"; // amber-700

  const role = isPt ? "Desenvolvedor Full-Stack" : "Full-Stack Developer";
  const tagline = isPt
    ? "Aplicações web e automações com IA."
    : "Web apps and AI automation.";
  const status = isPt ? "Aberto a conversar" : "Open to chat";
  const stack = "Bun · Node.js · TypeScript · Next.js · React · Astro";

  // Avatar — read from /public so the OG never depends on the network.
  let avatarSrc: string | undefined;
  try {
    const buf = await readFile(
      path.join(process.cwd(), "public", "avatar.png"),
    );
    avatarSrc = `data:image/png;base64,${buf.toString("base64")}`;
  } catch {
    avatarSrc = undefined;
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 80,
          background: PAPER,
          color: INK,
          fontFamily:
            "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto",
        }}
      >
        {/* Top: brand + status */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div
            style={{
              fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
              fontSize: 22,
              color: MUTED,
              display: "flex",
            }}
          >
            <span style={{ color: INK }}>kaua</span>
            <span>.dev.br</span>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
              fontSize: 16,
              color: MUTED,
              textTransform: "uppercase",
              letterSpacing: 3,
            }}
          >
            <div
              style={{
                width: 8,
                height: 8,
                borderRadius: 9999,
                background: "#16A34A",
              }}
            />
            <span>{status}</span>
          </div>
        </div>

        {/* Center: avatar + name + role + tagline */}
        <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
            {avatarSrc ? (
              <img
                src={avatarSrc}
                width={96}
                height={96}
                alt=""
                style={{
                  borderRadius: 9999,
                  border: `1px solid ${RULE}`,
                  display: "block",
                }}
              />
            ) : null}
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              <div
                style={{
                  fontSize: 64,
                  fontWeight: 600,
                  letterSpacing: -1.5,
                  lineHeight: 1.05,
                  color: INK,
                }}
              >
                {siteConfig.name}
              </div>
              <div
                style={{
                  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
                  fontSize: 20,
                  color: MUTED,
                }}
              >
                {role}
              </div>
            </div>
          </div>

          <div
            style={{
              fontSize: 38,
              lineHeight: 1.3,
              color: INK,
              maxWidth: 980,
            }}
          >
            {tagline}
          </div>
        </div>

        {/* Bottom: hairline + stack + handle */}
        <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
          <div
            style={{
              width: "100%",
              height: 1,
              background: RULE,
              display: "flex",
            }}
          />
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div
              style={{
                fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
                fontSize: 18,
                color: MUTED,
              }}
            >
              {stack}
            </div>
            <div
              style={{
                fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
                fontSize: 18,
                color: ACCENT,
                display: "flex",
              }}
            >
              {siteConfig.handle}
            </div>
          </div>
        </div>
      </div>
    ),
    { ...size },
  );
}
